[package]
name = "azure-vm-info"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
dotenv = "0.15.0"
json = "0.12.4"
lazy_static = "1.4.0"
regex = "1.9.5"
